# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SectionsDial.ui'
#
# Created by: PySide UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Sections_DockWidget(object):
    def setupUi(self, Sections_DockWidget):
        Sections_DockWidget.setObjectName(_fromUtf8("Sections_DockWidget"))
        Sections_DockWidget.resize(347, 328)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons:Sections.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Sections_DockWidget.setWindowIcon(icon)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.SectionsDial_doubleSpinBox_Distance = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.SectionsDial_doubleSpinBox_Distance.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SectionsDial_doubleSpinBox_Distance.setMinimum(0.01)
        self.SectionsDial_doubleSpinBox_Distance.setObjectName(_fromUtf8("SectionsDial_doubleSpinBox_Distance"))
        self.gridLayout_8.addWidget(self.SectionsDial_doubleSpinBox_Distance, 2, 1, 1, 1)
        self.SectionsDial_spinBox_Number = QtGui.QSpinBox(self.dockWidgetContents)
        self.SectionsDial_spinBox_Number.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SectionsDial_spinBox_Number.setMinimum(1)
        self.SectionsDial_spinBox_Number.setMaximum(999)
        self.SectionsDial_spinBox_Number.setProperty("value", 1)
        self.SectionsDial_spinBox_Number.setObjectName(_fromUtf8("SectionsDial_spinBox_Number"))
        self.gridLayout_8.addWidget(self.SectionsDial_spinBox_Number, 1, 1, 1, 1)
        self.SectionsDial_doubleSpinBox_StartOffset = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.SectionsDial_doubleSpinBox_StartOffset.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SectionsDial_doubleSpinBox_StartOffset.setObjectName(_fromUtf8("SectionsDial_doubleSpinBox_StartOffset"))
        self.gridLayout_8.addWidget(self.SectionsDial_doubleSpinBox_StartOffset, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 1)
        self.SectionsDial_checkBox_Number = QtGui.QCheckBox(self.dockWidgetContents)
        self.SectionsDial_checkBox_Number.setObjectName(_fromUtf8("SectionsDial_checkBox_Number"))
        self.gridLayout_8.addWidget(self.SectionsDial_checkBox_Number, 1, 0, 1, 1)
        self.SectionsDial_checkBox_Distance = QtGui.QCheckBox(self.dockWidgetContents)
        self.SectionsDial_checkBox_Distance.setObjectName(_fromUtf8("SectionsDial_checkBox_Distance"))
        self.gridLayout_8.addWidget(self.SectionsDial_checkBox_Distance, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 3, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setMaximumSize(QtCore.QSize(281, 16777215))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.SectionsDial_info_selected_object = QtGui.QLineEdit(self.groupBox_2)
        self.SectionsDial_info_selected_object.setEnabled(False)
        self.SectionsDial_info_selected_object.setMinimumSize(QtCore.QSize(0, 0))
        self.SectionsDial_info_selected_object.setMaximumSize(QtCore.QSize(250, 16777215))
        self.SectionsDial_info_selected_object.setObjectName(_fromUtf8("SectionsDial_info_selected_object"))
        self.gridLayout_7.addWidget(self.SectionsDial_info_selected_object, 0, 0, 1, 1)
        self.SectionsDial_button_select_object = QtGui.QPushButton(self.groupBox_2)
        self.SectionsDial_button_select_object.setMinimumSize(QtCore.QSize(130, 31))
        self.SectionsDial_button_select_object.setMaximumSize(QtCore.QSize(250, 40))
        self.SectionsDial_button_select_object.setObjectName(_fromUtf8("SectionsDial_button_select_object"))
        self.gridLayout_7.addWidget(self.SectionsDial_button_select_object, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 1, 1, 2, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.SectionsDial_radioButton_XY = QtGui.QRadioButton(self.dockWidgetContents)
        self.SectionsDial_radioButton_XY.setChecked(True)
        self.SectionsDial_radioButton_XY.setObjectName(_fromUtf8("SectionsDial_radioButton_XY"))
        self.buttonGroup = QtGui.QButtonGroup(Sections_DockWidget)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.SectionsDial_radioButton_XY)
        self.gridLayout_14.addWidget(self.SectionsDial_radioButton_XY, 0, 0, 1, 1)
        self.SectionsDial_radioButton_XZ = QtGui.QRadioButton(self.dockWidgetContents)
        self.SectionsDial_radioButton_XZ.setObjectName(_fromUtf8("SectionsDial_radioButton_XZ"))
        self.buttonGroup.addButton(self.SectionsDial_radioButton_XZ)
        self.gridLayout_14.addWidget(self.SectionsDial_radioButton_XZ, 1, 0, 1, 1)
        self.SectionsDial_radioButton_YZ = QtGui.QRadioButton(self.dockWidgetContents)
        self.SectionsDial_radioButton_YZ.setObjectName(_fromUtf8("SectionsDial_radioButton_YZ"))
        self.buttonGroup.addButton(self.SectionsDial_radioButton_YZ)
        self.gridLayout_14.addWidget(self.SectionsDial_radioButton_YZ, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_14, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.SectionsDial_button_OK = QtGui.QPushButton(self.dockWidgetContents)
        self.SectionsDial_button_OK.setObjectName(_fromUtf8("SectionsDial_button_OK"))
        self.horizontalLayout.addWidget(self.SectionsDial_button_OK)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        Sections_DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(Sections_DockWidget)
        QtCore.QMetaObject.connectSlotsByName(Sections_DockWidget)

    def retranslateUi(self, Sections_DockWidget):
        Sections_DockWidget.setWindowTitle(_translate("Sections_DockWidget", "Sections", None))
        self.label.setText(_translate("Sections_DockWidget", "Start offset", None))
        self.SectionsDial_checkBox_Number.setText(_translate("Sections_DockWidget", "calculate number", None))
        self.SectionsDial_checkBox_Distance.setText(_translate("Sections_DockWidget", "calculate distance", None))
        self.groupBox_2.setTitle(_translate("Sections_DockWidget", "Object", None))
        self.SectionsDial_button_select_object.setText(_translate("Sections_DockWidget", "Select Object", None))
        self.SectionsDial_radioButton_XY.setText(_translate("Sections_DockWidget", "XY", None))
        self.SectionsDial_radioButton_XZ.setText(_translate("Sections_DockWidget", "XZ", None))
        self.SectionsDial_radioButton_YZ.setText(_translate("Sections_DockWidget", "YZ", None))
        self.SectionsDial_button_OK.setText(_translate("Sections_DockWidget", "OK", None))

