# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SectionsDial.ui'
#
# Created: Mon Apr 30 03:19:56 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Sections_DockWidget(object):
    def setupUi(self, Sections_DockWidget):
        Sections_DockWidget.setObjectName("Sections_DockWidget")
        Sections_DockWidget.resize(347, 328)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:Sections.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Sections_DockWidget.setWindowIcon(icon)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.SectionsDial_doubleSpinBox_Distance = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.SectionsDial_doubleSpinBox_Distance.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SectionsDial_doubleSpinBox_Distance.setMinimum(0.01)
        self.SectionsDial_doubleSpinBox_Distance.setObjectName("SectionsDial_doubleSpinBox_Distance")
        self.gridLayout_8.addWidget(self.SectionsDial_doubleSpinBox_Distance, 2, 1, 1, 1)
        self.SectionsDial_spinBox_Number = QtGui.QSpinBox(self.dockWidgetContents)
        self.SectionsDial_spinBox_Number.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SectionsDial_spinBox_Number.setMinimum(1)
        self.SectionsDial_spinBox_Number.setMaximum(999)
        self.SectionsDial_spinBox_Number.setProperty("value", 1)
        self.SectionsDial_spinBox_Number.setObjectName("SectionsDial_spinBox_Number")
        self.gridLayout_8.addWidget(self.SectionsDial_spinBox_Number, 1, 1, 1, 1)
        self.SectionsDial_doubleSpinBox_StartOffset = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.SectionsDial_doubleSpinBox_StartOffset.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SectionsDial_doubleSpinBox_StartOffset.setObjectName("SectionsDial_doubleSpinBox_StartOffset")
        self.gridLayout_8.addWidget(self.SectionsDial_doubleSpinBox_StartOffset, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 1)
        self.SectionsDial_checkBox_Number = QtGui.QCheckBox(self.dockWidgetContents)
        self.SectionsDial_checkBox_Number.setObjectName("SectionsDial_checkBox_Number")
        self.gridLayout_8.addWidget(self.SectionsDial_checkBox_Number, 1, 0, 1, 1)
        self.SectionsDial_checkBox_Distance = QtGui.QCheckBox(self.dockWidgetContents)
        self.SectionsDial_checkBox_Distance.setObjectName("SectionsDial_checkBox_Distance")
        self.gridLayout_8.addWidget(self.SectionsDial_checkBox_Distance, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setMaximumSize(QtCore.QSize(281, 16777215))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.SectionsDial_info_selected_object = QtGui.QLineEdit(self.groupBox_2)
        self.SectionsDial_info_selected_object.setEnabled(False)
        self.SectionsDial_info_selected_object.setMinimumSize(QtCore.QSize(0, 0))
        self.SectionsDial_info_selected_object.setMaximumSize(QtCore.QSize(250, 16777215))
        self.SectionsDial_info_selected_object.setObjectName("SectionsDial_info_selected_object")
        self.gridLayout_7.addWidget(self.SectionsDial_info_selected_object, 0, 0, 1, 1)
        self.SectionsDial_button_select_object = QtGui.QPushButton(self.groupBox_2)
        self.SectionsDial_button_select_object.setMinimumSize(QtCore.QSize(130, 31))
        self.SectionsDial_button_select_object.setMaximumSize(QtCore.QSize(250, 40))
        self.SectionsDial_button_select_object.setObjectName("SectionsDial_button_select_object")
        self.gridLayout_7.addWidget(self.SectionsDial_button_select_object, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 1, 1, 2, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.SectionsDial_button_OK = QtGui.QPushButton(self.dockWidgetContents)
        self.SectionsDial_button_OK.setObjectName("SectionsDial_button_OK")
        self.horizontalLayout.addWidget(self.SectionsDial_button_OK)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        Sections_DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(Sections_DockWidget)
        QtCore.QMetaObject.connectSlotsByName(Sections_DockWidget)

    def retranslateUi(self, Sections_DockWidget):
        Sections_DockWidget.setWindowTitle(QtGui.QApplication.translate("Sections_DockWidget", "DockWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Sections_DockWidget", "Start offset", None, QtGui.QApplication.UnicodeUTF8))
        self.SectionsDial_checkBox_Number.setText(QtGui.QApplication.translate("Sections_DockWidget", "calculate number", None, QtGui.QApplication.UnicodeUTF8))
        self.SectionsDial_checkBox_Distance.setText(QtGui.QApplication.translate("Sections_DockWidget", "calculate distance", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Sections_DockWidget", "Object", None, QtGui.QApplication.UnicodeUTF8))
        self.SectionsDial_button_select_object.setText(QtGui.QApplication.translate("Sections_DockWidget", "Select Object", None, QtGui.QApplication.UnicodeUTF8))
        self.SectionsDial_button_OK.setText(QtGui.QApplication.translate("Sections_DockWidget", "OK", None, QtGui.QApplication.UnicodeUTF8))

