# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WingDial.ui'
#
# Created: Sun Apr 29 20:43:12 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(418, 582)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:Aile-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DockWidget.setWindowIcon(icon)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.Section_tab = QtGui.QWidget()
        self.Section_tab.setObjectName("Section_tab")
        self.gridLayout_4 = QtGui.QGridLayout(self.Section_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Section_horizontalSlider = QtGui.QSlider(self.Section_tab)
        self.Section_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Section_horizontalSlider.setObjectName("Section_horizontalSlider")
        self.gridLayout_4.addWidget(self.Section_horizontalSlider, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Section_button_apply = QtGui.QPushButton(self.Section_tab)
        self.Section_button_apply.setAutoDefault(False)
        self.Section_button_apply.setFlat(False)
        self.Section_button_apply.setObjectName("Section_button_apply")
        self.horizontalLayout.addWidget(self.Section_button_apply)
        self.Section_button_reset = QtGui.QPushButton(self.Section_tab)
        self.Section_button_reset.setAutoDefault(False)
        self.Section_button_reset.setObjectName("Section_button_reset")
        self.horizontalLayout.addWidget(self.Section_button_reset)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_4.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.Section_dial = QtGui.QDial(self.Section_tab)
        self.Section_dial.setObjectName("Section_dial")
        self.gridLayout_4.addWidget(self.Section_dial, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.Section_tab)
        self.groupBox.setMaximumSize(QtCore.QSize(281, 16777215))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Section_button_select_object = QtGui.QPushButton(self.groupBox)
        self.Section_button_select_object.setMinimumSize(QtCore.QSize(130, 31))
        self.Section_button_select_object.setMaximumSize(QtCore.QSize(250, 40))
        self.Section_button_select_object.setObjectName("Section_button_select_object")
        self.gridLayout_2.addWidget(self.Section_button_select_object, 1, 0, 1, 1)
        self.Section_info_selected_object = QtGui.QLineEdit(self.groupBox)
        self.Section_info_selected_object.setEnabled(False)
        self.Section_info_selected_object.setMinimumSize(QtCore.QSize(0, 0))
        self.Section_info_selected_object.setMaximumSize(QtCore.QSize(250, 16777215))
        self.Section_info_selected_object.setObjectName("Section_info_selected_object")
        self.gridLayout_2.addWidget(self.Section_info_selected_object, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.Section_doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.Section_doubleSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Section_doubleSpinBox.setObjectName("Section_doubleSpinBox")
        self.gridLayout_3.addWidget(self.Section_doubleSpinBox, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 5, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons:Section.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Section_tab, icon1, "")
        self.CutWire_tab = QtGui.QWidget()
        self.CutWire_tab.setObjectName("CutWire_tab")
        self.gridLayout_10 = QtGui.QGridLayout(self.CutWire_tab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.CutWire_button_apply = QtGui.QPushButton(self.CutWire_tab)
        self.CutWire_button_apply.setAutoDefault(False)
        self.CutWire_button_apply.setFlat(False)
        self.CutWire_button_apply.setObjectName("CutWire_button_apply")
        self.horizontalLayout_3.addWidget(self.CutWire_button_apply)
        self.CutWire_button_reset = QtGui.QPushButton(self.CutWire_tab)
        self.CutWire_button_reset.setAutoDefault(False)
        self.CutWire_button_reset.setObjectName("CutWire_button_reset")
        self.horizontalLayout_3.addWidget(self.CutWire_button_reset)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.gridLayout_10.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.CutWire_tab)
        self.groupBox_2.setMaximumSize(QtCore.QSize(281, 16777215))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.CutWire_button_select_object = QtGui.QPushButton(self.groupBox_2)
        self.CutWire_button_select_object.setMinimumSize(QtCore.QSize(130, 31))
        self.CutWire_button_select_object.setMaximumSize(QtCore.QSize(250, 40))
        self.CutWire_button_select_object.setObjectName("CutWire_button_select_object")
        self.gridLayout_7.addWidget(self.CutWire_button_select_object, 1, 0, 1, 1)
        self.CutWire_info_selected_object = QtGui.QLineEdit(self.groupBox_2)
        self.CutWire_info_selected_object.setEnabled(False)
        self.CutWire_info_selected_object.setMinimumSize(QtCore.QSize(0, 0))
        self.CutWire_info_selected_object.setMaximumSize(QtCore.QSize(250, 16777215))
        self.CutWire_info_selected_object.setObjectName("CutWire_info_selected_object")
        self.gridLayout_7.addWidget(self.CutWire_info_selected_object, 0, 0, 1, 1)
        self.CutWire_comboBox = QtGui.QComboBox(self.groupBox_2)
        self.CutWire_comboBox.setObjectName("CutWire_comboBox")
        self.CutWire_comboBox.addItem("")
        self.CutWire_comboBox.addItem("")
        self.CutWire_comboBox.addItem("")
        self.gridLayout_7.addWidget(self.CutWire_comboBox, 2, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 1, 1, 2, 1)
        self.gridLayout_10.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_2 = QtGui.QLabel(self.CutWire_tab)
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.CutWire_doubleSpinBox_start = QtGui.QDoubleSpinBox(self.CutWire_tab)
        self.CutWire_doubleSpinBox_start.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CutWire_doubleSpinBox_start.setObjectName("CutWire_doubleSpinBox_start")
        self.gridLayout_8.addWidget(self.CutWire_doubleSpinBox_start, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_8)
        self.CutWire_horizontalSlider_start = QtGui.QSlider(self.CutWire_tab)
        self.CutWire_horizontalSlider_start.setOrientation(QtCore.Qt.Horizontal)
        self.CutWire_horizontalSlider_start.setObjectName("CutWire_horizontalSlider_start")
        self.verticalLayout_2.addWidget(self.CutWire_horizontalSlider_start)
        self.CutWire_dial_start = QtGui.QDial(self.CutWire_tab)
        self.CutWire_dial_start.setObjectName("CutWire_dial_start")
        self.verticalLayout_2.addWidget(self.CutWire_dial_start)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_3 = QtGui.QLabel(self.CutWire_tab)
        self.label_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 0, 0, 1, 1)
        self.CutWire_doubleSpinBox_end = QtGui.QDoubleSpinBox(self.CutWire_tab)
        self.CutWire_doubleSpinBox_end.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CutWire_doubleSpinBox_end.setObjectName("CutWire_doubleSpinBox_end")
        self.gridLayout_9.addWidget(self.CutWire_doubleSpinBox_end, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_9)
        self.CutWire_horizontalSlider_end = QtGui.QSlider(self.CutWire_tab)
        self.CutWire_horizontalSlider_end.setOrientation(QtCore.Qt.Horizontal)
        self.CutWire_horizontalSlider_end.setObjectName("CutWire_horizontalSlider_end")
        self.verticalLayout_2.addWidget(self.CutWire_horizontalSlider_end)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.CutWire_CheckBox_gap = QtGui.QCheckBox(self.CutWire_tab)
        self.CutWire_CheckBox_gap.setObjectName("CutWire_CheckBox_gap")
        self.gridLayout_11.addWidget(self.CutWire_CheckBox_gap, 0, 0, 1, 1)
        self.CutWire_dial_end = QtGui.QDial(self.CutWire_tab)
        self.CutWire_dial_end.setObjectName("CutWire_dial_end")
        self.gridLayout_11.addWidget(self.CutWire_dial_end, 0, 2, 1, 1)
        self.CutWire_doubleSpinBox_gap = QtGui.QDoubleSpinBox(self.CutWire_tab)
        self.CutWire_doubleSpinBox_gap.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CutWire_doubleSpinBox_gap.setObjectName("CutWire_doubleSpinBox_gap")
        self.gridLayout_11.addWidget(self.CutWire_doubleSpinBox_gap, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_11)
        self.gridLayout_10.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem5, 3, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons:CutWire-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.CutWire_tab, icon2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.Close_button = QtGui.QPushButton(self.dockWidgetContents)
        self.Close_button.setObjectName("Close_button")
        self.horizontalLayout_2.addWidget(self.Close_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(QtGui.QApplication.translate("DockWidget", "Wing toolkit", None, QtGui.QApplication.UnicodeUTF8))
        self.Section_button_apply.setText(QtGui.QApplication.translate("DockWidget", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.Section_button_reset.setText(QtGui.QApplication.translate("DockWidget", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DockWidget", "Object", None, QtGui.QApplication.UnicodeUTF8))
        self.Section_button_select_object.setText(QtGui.QApplication.translate("DockWidget", "Select Object", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DockWidget", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Section_tab), QtGui.QApplication.translate("DockWidget", "Section", None, QtGui.QApplication.UnicodeUTF8))
        self.CutWire_button_apply.setText(QtGui.QApplication.translate("DockWidget", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.CutWire_button_reset.setText(QtGui.QApplication.translate("DockWidget", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("DockWidget", "Object", None, QtGui.QApplication.UnicodeUTF8))
        self.CutWire_button_select_object.setText(QtGui.QApplication.translate("DockWidget", "Select Object", None, QtGui.QApplication.UnicodeUTF8))
        self.CutWire_comboBox.setItemText(0, QtGui.QApplication.translate("DockWidget", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.CutWire_comboBox.setItemText(1, QtGui.QApplication.translate("DockWidget", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.CutWire_comboBox.setItemText(2, QtGui.QApplication.translate("DockWidget", "Both", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DockWidget", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DockWidget", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.CutWire_CheckBox_gap.setText(QtGui.QApplication.translate("DockWidget", "constant gap", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CutWire_tab), QtGui.QApplication.translate("DockWidget", "Cut wire", None, QtGui.QApplication.UnicodeUTF8))
        self.Close_button.setText(QtGui.QApplication.translate("DockWidget", "Close", None, QtGui.QApplication.UnicodeUTF8))

