# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WingDial.ui'
#
# Created by: PySide UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(416, 804)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons:Aile-icon.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DockWidget.setWindowIcon(icon)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setIconSize(QtCore.QSize(32, 16))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Section_tab = QtGui.QWidget()
        self.Section_tab.setObjectName(_fromUtf8("Section_tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.Section_tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.Section_dial = QtGui.QDial(self.Section_tab)
        self.Section_dial.setObjectName(_fromUtf8("Section_dial"))
        self.gridLayout_4.addWidget(self.Section_dial, 2, 0, 1, 1)
        self.Section_horizontalSlider = QtGui.QSlider(self.Section_tab)
        self.Section_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Section_horizontalSlider.setObjectName(_fromUtf8("Section_horizontalSlider"))
        self.gridLayout_4.addWidget(self.Section_horizontalSlider, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 5, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Section_button_apply = QtGui.QPushButton(self.Section_tab)
        self.Section_button_apply.setAutoDefault(False)
        self.Section_button_apply.setFlat(False)
        self.Section_button_apply.setObjectName(_fromUtf8("Section_button_apply"))
        self.horizontalLayout.addWidget(self.Section_button_apply)
        self.Section_button_reset = QtGui.QPushButton(self.Section_tab)
        self.Section_button_reset.setAutoDefault(False)
        self.Section_button_reset.setObjectName(_fromUtf8("Section_button_reset"))
        self.horizontalLayout.addWidget(self.Section_button_reset)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.Section_tab)
        self.groupBox.setMaximumSize(QtCore.QSize(281, 16777215))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.Section_button_select_object = QtGui.QPushButton(self.groupBox)
        self.Section_button_select_object.setMinimumSize(QtCore.QSize(130, 31))
        self.Section_button_select_object.setMaximumSize(QtCore.QSize(250, 40))
        self.Section_button_select_object.setObjectName(_fromUtf8("Section_button_select_object"))
        self.gridLayout_3.addWidget(self.Section_button_select_object, 1, 0, 1, 1)
        self.Section_info_selected_object = QtGui.QLineEdit(self.groupBox)
        self.Section_info_selected_object.setEnabled(False)
        self.Section_info_selected_object.setMinimumSize(QtCore.QSize(0, 0))
        self.Section_info_selected_object.setMaximumSize(QtCore.QSize(250, 16777215))
        self.Section_info_selected_object.setObjectName(_fromUtf8("Section_info_selected_object"))
        self.gridLayout_3.addWidget(self.Section_info_selected_object, 0, 0, 1, 1)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_13.addWidget(self.label, 0, 0, 1, 1)
        self.Section_doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.Section_doubleSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Section_doubleSpinBox.setObjectName(_fromUtf8("Section_doubleSpinBox"))
        self.gridLayout_13.addWidget(self.Section_doubleSpinBox, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_13, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 3, 1, 1)
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.Section_radioButton_XY = QtGui.QRadioButton(self.Section_tab)
        self.Section_radioButton_XY.setChecked(True)
        self.Section_radioButton_XY.setObjectName(_fromUtf8("Section_radioButton_XY"))
        self.buttonGroup = QtGui.QButtonGroup(DockWidget)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.Section_radioButton_XY)
        self.gridLayout_14.addWidget(self.Section_radioButton_XY, 0, 0, 1, 1)
        self.Section_radioButton_XZ = QtGui.QRadioButton(self.Section_tab)
        self.Section_radioButton_XZ.setObjectName(_fromUtf8("Section_radioButton_XZ"))
        self.buttonGroup.addButton(self.Section_radioButton_XZ)
        self.gridLayout_14.addWidget(self.Section_radioButton_XZ, 1, 0, 1, 1)
        self.Section_radioButton_YZ = QtGui.QRadioButton(self.Section_tab)
        self.Section_radioButton_YZ.setObjectName(_fromUtf8("Section_radioButton_YZ"))
        self.buttonGroup.addButton(self.Section_radioButton_YZ)
        self.gridLayout_14.addWidget(self.Section_radioButton_YZ, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_14, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons:Section.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Section_tab, icon1, _fromUtf8(""))
        self.CutWire_tab = QtGui.QWidget()
        self.CutWire_tab.setObjectName(_fromUtf8("CutWire_tab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.CutWire_tab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.CutWire_button_apply = QtGui.QPushButton(self.CutWire_tab)
        self.CutWire_button_apply.setAutoDefault(False)
        self.CutWire_button_apply.setFlat(False)
        self.CutWire_button_apply.setObjectName(_fromUtf8("CutWire_button_apply"))
        self.horizontalLayout_3.addWidget(self.CutWire_button_apply)
        self.CutWire_button_reset = QtGui.QPushButton(self.CutWire_tab)
        self.CutWire_button_reset.setAutoDefault(False)
        self.CutWire_button_reset.setObjectName(_fromUtf8("CutWire_button_reset"))
        self.horizontalLayout_3.addWidget(self.CutWire_button_reset)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.gridLayout_10.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.CutWire_doubleSpinBox_start = QtGui.QDoubleSpinBox(self.CutWire_tab)
        self.CutWire_doubleSpinBox_start.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CutWire_doubleSpinBox_start.setObjectName(_fromUtf8("CutWire_doubleSpinBox_start"))
        self.gridLayout_8.addWidget(self.CutWire_doubleSpinBox_start, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.CutWire_tab)
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_8)
        self.CutWire_horizontalSlider_start = QtGui.QSlider(self.CutWire_tab)
        self.CutWire_horizontalSlider_start.setOrientation(QtCore.Qt.Horizontal)
        self.CutWire_horizontalSlider_start.setObjectName(_fromUtf8("CutWire_horizontalSlider_start"))
        self.verticalLayout_2.addWidget(self.CutWire_horizontalSlider_start)
        self.CutWire_dial_start = QtGui.QDial(self.CutWire_tab)
        self.CutWire_dial_start.setObjectName(_fromUtf8("CutWire_dial_start"))
        self.verticalLayout_2.addWidget(self.CutWire_dial_start)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_3 = QtGui.QLabel(self.CutWire_tab)
        self.label_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_9.addWidget(self.label_3, 0, 0, 1, 1)
        self.CutWire_doubleSpinBox_end = QtGui.QDoubleSpinBox(self.CutWire_tab)
        self.CutWire_doubleSpinBox_end.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CutWire_doubleSpinBox_end.setObjectName(_fromUtf8("CutWire_doubleSpinBox_end"))
        self.gridLayout_9.addWidget(self.CutWire_doubleSpinBox_end, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_9)
        self.CutWire_horizontalSlider_end = QtGui.QSlider(self.CutWire_tab)
        self.CutWire_horizontalSlider_end.setOrientation(QtCore.Qt.Horizontal)
        self.CutWire_horizontalSlider_end.setObjectName(_fromUtf8("CutWire_horizontalSlider_end"))
        self.verticalLayout_2.addWidget(self.CutWire_horizontalSlider_end)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.CutWire_CheckBox_gap = QtGui.QCheckBox(self.CutWire_tab)
        self.CutWire_CheckBox_gap.setObjectName(_fromUtf8("CutWire_CheckBox_gap"))
        self.gridLayout_11.addWidget(self.CutWire_CheckBox_gap, 0, 0, 1, 1)
        self.CutWire_dial_end = QtGui.QDial(self.CutWire_tab)
        self.CutWire_dial_end.setObjectName(_fromUtf8("CutWire_dial_end"))
        self.gridLayout_11.addWidget(self.CutWire_dial_end, 0, 2, 1, 1)
        self.CutWire_doubleSpinBox_gap = QtGui.QDoubleSpinBox(self.CutWire_tab)
        self.CutWire_doubleSpinBox_gap.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CutWire_doubleSpinBox_gap.setObjectName(_fromUtf8("CutWire_doubleSpinBox_gap"))
        self.gridLayout_11.addWidget(self.CutWire_doubleSpinBox_gap, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_11)
        self.gridLayout_10.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem7, 3, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.CutWire_tab)
        self.groupBox_2.setMaximumSize(QtCore.QSize(281, 16777215))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.CutWire_button_select_object = QtGui.QPushButton(self.groupBox_2)
        self.CutWire_button_select_object.setMinimumSize(QtCore.QSize(130, 31))
        self.CutWire_button_select_object.setMaximumSize(QtCore.QSize(250, 40))
        self.CutWire_button_select_object.setObjectName(_fromUtf8("CutWire_button_select_object"))
        self.gridLayout_12.addWidget(self.CutWire_button_select_object, 1, 0, 1, 1)
        self.CutWire_info_selected_object = QtGui.QLineEdit(self.groupBox_2)
        self.CutWire_info_selected_object.setEnabled(False)
        self.CutWire_info_selected_object.setMinimumSize(QtCore.QSize(0, 0))
        self.CutWire_info_selected_object.setMaximumSize(QtCore.QSize(250, 16777215))
        self.CutWire_info_selected_object.setObjectName(_fromUtf8("CutWire_info_selected_object"))
        self.gridLayout_12.addWidget(self.CutWire_info_selected_object, 0, 0, 1, 1)
        self.CutWire_comboBox = QtGui.QComboBox(self.groupBox_2)
        self.CutWire_comboBox.setObjectName(_fromUtf8("CutWire_comboBox"))
        self.CutWire_comboBox.addItem(_fromUtf8(""))
        self.CutWire_comboBox.addItem(_fromUtf8(""))
        self.CutWire_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_12.addWidget(self.CutWire_comboBox, 2, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_12, 1, 1, 2, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem9, 0, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons:CutWireDial-icon.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.CutWire_tab, icon2, _fromUtf8(""))
        self.LeadingEdge_tab = QtGui.QWidget()
        self.LeadingEdge_tab.setObjectName(_fromUtf8("LeadingEdge_tab"))
        self.gridLayout_18 = QtGui.QGridLayout(self.LeadingEdge_tab)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.groupBox_3 = QtGui.QGroupBox(self.LeadingEdge_tab)
        self.groupBox_3.setMaximumSize(QtCore.QSize(281, 16777215))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.LeadingEdge_info_selected_object = QtGui.QLineEdit(self.groupBox_3)
        self.LeadingEdge_info_selected_object.setEnabled(False)
        self.LeadingEdge_info_selected_object.setMinimumSize(QtCore.QSize(0, 0))
        self.LeadingEdge_info_selected_object.setMaximumSize(QtCore.QSize(250, 16777215))
        self.LeadingEdge_info_selected_object.setObjectName(_fromUtf8("LeadingEdge_info_selected_object"))
        self.gridLayout_16.addWidget(self.LeadingEdge_info_selected_object, 0, 0, 1, 1)
        self.LeadingEdge_button_select_object = QtGui.QPushButton(self.groupBox_3)
        self.LeadingEdge_button_select_object.setMinimumSize(QtCore.QSize(130, 31))
        self.LeadingEdge_button_select_object.setMaximumSize(QtCore.QSize(250, 40))
        self.LeadingEdge_button_select_object.setObjectName(_fromUtf8("LeadingEdge_button_select_object"))
        self.gridLayout_16.addWidget(self.LeadingEdge_button_select_object, 1, 0, 1, 1)
        self.LeadingEdge_comboBox = QtGui.QComboBox(self.groupBox_3)
        self.LeadingEdge_comboBox.setObjectName(_fromUtf8("LeadingEdge_comboBox"))
        self.LeadingEdge_comboBox.addItem(_fromUtf8(""))
        self.LeadingEdge_comboBox.addItem(_fromUtf8(""))
        self.LeadingEdge_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.LeadingEdge_comboBox, 2, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_3, 0, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem10, 0, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem11, 0, 2, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_21 = QtGui.QGridLayout()
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.gridLayout_22 = QtGui.QGridLayout()
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.label_5 = QtGui.QLabel(self.LeadingEdge_tab)
        self.label_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_22.addWidget(self.label_5, 0, 0, 1, 1)
        self.LeadingEdge_doubleSpinBox_Rootstart = QtGui.QDoubleSpinBox(self.LeadingEdge_tab)
        self.LeadingEdge_doubleSpinBox_Rootstart.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LeadingEdge_doubleSpinBox_Rootstart.setObjectName(_fromUtf8("LeadingEdge_doubleSpinBox_Rootstart"))
        self.gridLayout_22.addWidget(self.LeadingEdge_doubleSpinBox_Rootstart, 0, 1, 1, 1)
        self.LeadingEdge_dial_Rootstart = QtGui.QDial(self.LeadingEdge_tab)
        self.LeadingEdge_dial_Rootstart.setObjectName(_fromUtf8("LeadingEdge_dial_Rootstart"))
        self.gridLayout_22.addWidget(self.LeadingEdge_dial_Rootstart, 0, 2, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_22, 0, 0, 1, 1)
        self.gridLayout_23 = QtGui.QGridLayout()
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.label_6 = QtGui.QLabel(self.LeadingEdge_tab)
        self.label_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_23.addWidget(self.label_6, 0, 0, 1, 1)
        self.LeadingEdge_doubleSpinBox_Rootend = QtGui.QDoubleSpinBox(self.LeadingEdge_tab)
        self.LeadingEdge_doubleSpinBox_Rootend.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LeadingEdge_doubleSpinBox_Rootend.setObjectName(_fromUtf8("LeadingEdge_doubleSpinBox_Rootend"))
        self.gridLayout_23.addWidget(self.LeadingEdge_doubleSpinBox_Rootend, 0, 1, 1, 1)
        self.LeadingEdge_dial_Rootend = QtGui.QDial(self.LeadingEdge_tab)
        self.LeadingEdge_dial_Rootend.setObjectName(_fromUtf8("LeadingEdge_dial_Rootend"))
        self.gridLayout_23.addWidget(self.LeadingEdge_dial_Rootend, 0, 2, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_23, 2, 0, 1, 1)
        self.LeadingEdge_horizontalSlider_Rootstart = QtGui.QSlider(self.LeadingEdge_tab)
        self.LeadingEdge_horizontalSlider_Rootstart.setOrientation(QtCore.Qt.Horizontal)
        self.LeadingEdge_horizontalSlider_Rootstart.setObjectName(_fromUtf8("LeadingEdge_horizontalSlider_Rootstart"))
        self.gridLayout_21.addWidget(self.LeadingEdge_horizontalSlider_Rootstart, 1, 0, 1, 1)
        self.LeadingEdge_horizontalSlider_Rootend = QtGui.QSlider(self.LeadingEdge_tab)
        self.LeadingEdge_horizontalSlider_Rootend.setOrientation(QtCore.Qt.Horizontal)
        self.LeadingEdge_horizontalSlider_Rootend.setObjectName(_fromUtf8("LeadingEdge_horizontalSlider_Rootend"))
        self.gridLayout_21.addWidget(self.LeadingEdge_horizontalSlider_Rootend, 3, 0, 1, 1)
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.LeadingEdge_doubleSpinBox_gap = QtGui.QDoubleSpinBox(self.LeadingEdge_tab)
        self.LeadingEdge_doubleSpinBox_gap.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LeadingEdge_doubleSpinBox_gap.setObjectName(_fromUtf8("LeadingEdge_doubleSpinBox_gap"))
        self.gridLayout_20.addWidget(self.LeadingEdge_doubleSpinBox_gap, 0, 2, 1, 1)
        self.LeadingEdge_CheckBox_gap = QtGui.QCheckBox(self.LeadingEdge_tab)
        self.LeadingEdge_CheckBox_gap.setObjectName(_fromUtf8("LeadingEdge_CheckBox_gap"))
        self.gridLayout_20.addWidget(self.LeadingEdge_CheckBox_gap, 0, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_20, 4, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_21, 1, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem12, 6, 0, 1, 1)
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem13, 0, 0, 1, 1)
        self.LeadingEdge_button_apply = QtGui.QPushButton(self.LeadingEdge_tab)
        self.LeadingEdge_button_apply.setAutoDefault(False)
        self.LeadingEdge_button_apply.setFlat(False)
        self.LeadingEdge_button_apply.setObjectName(_fromUtf8("LeadingEdge_button_apply"))
        self.gridLayout_19.addWidget(self.LeadingEdge_button_apply, 0, 1, 1, 1)
        self.LeadingEdge_button_reset = QtGui.QPushButton(self.LeadingEdge_tab)
        self.LeadingEdge_button_reset.setAutoDefault(False)
        self.LeadingEdge_button_reset.setObjectName(_fromUtf8("LeadingEdge_button_reset"))
        self.gridLayout_19.addWidget(self.LeadingEdge_button_reset, 0, 2, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem14, 0, 3, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_19, 5, 0, 1, 1)
        self.gridLayout_24 = QtGui.QGridLayout()
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.gridLayout_25 = QtGui.QGridLayout()
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.LeadingEdge_dial_Tipstart = QtGui.QDial(self.LeadingEdge_tab)
        self.LeadingEdge_dial_Tipstart.setObjectName(_fromUtf8("LeadingEdge_dial_Tipstart"))
        self.gridLayout_25.addWidget(self.LeadingEdge_dial_Tipstart, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.LeadingEdge_tab)
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_25.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_26 = QtGui.QGridLayout()
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.LeadingEdge_doubleSpinBox_Tipstart = QtGui.QDoubleSpinBox(self.LeadingEdge_tab)
        self.LeadingEdge_doubleSpinBox_Tipstart.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LeadingEdge_doubleSpinBox_Tipstart.setObjectName(_fromUtf8("LeadingEdge_doubleSpinBox_Tipstart"))
        self.gridLayout_26.addWidget(self.LeadingEdge_doubleSpinBox_Tipstart, 0, 0, 1, 1)
        self.LeadingEdge_CheckBox_EqualRoot = QtGui.QCheckBox(self.LeadingEdge_tab)
        self.LeadingEdge_CheckBox_EqualRoot.setObjectName(_fromUtf8("LeadingEdge_CheckBox_EqualRoot"))
        self.gridLayout_26.addWidget(self.LeadingEdge_CheckBox_EqualRoot, 1, 0, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_26, 0, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_25, 0, 0, 1, 1)
        self.LeadingEdge_horizontalSlider_Tipstart = QtGui.QSlider(self.LeadingEdge_tab)
        self.LeadingEdge_horizontalSlider_Tipstart.setOrientation(QtCore.Qt.Horizontal)
        self.LeadingEdge_horizontalSlider_Tipstart.setObjectName(_fromUtf8("LeadingEdge_horizontalSlider_Tipstart"))
        self.gridLayout_24.addWidget(self.LeadingEdge_horizontalSlider_Tipstart, 1, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_24, 3, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons:LeadingEdge-icon.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.LeadingEdge_tab, icon3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.Close_button = QtGui.QPushButton(self.dockWidgetContents)
        self.Close_button.setObjectName(_fromUtf8("Close_button"))
        self.horizontalLayout_2.addWidget(self.Close_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "Wing toolkit", None))
        self.Section_button_apply.setText(_translate("DockWidget", "Apply", None))
        self.Section_button_reset.setText(_translate("DockWidget", "Reset", None))
        self.groupBox.setTitle(_translate("DockWidget", "Object", None))
        self.Section_button_select_object.setText(_translate("DockWidget", "Select Object", None))
        self.label.setText(_translate("DockWidget", "Value", None))
        self.Section_radioButton_XY.setText(_translate("DockWidget", "XY", None))
        self.Section_radioButton_XZ.setText(_translate("DockWidget", "XZ", None))
        self.Section_radioButton_YZ.setText(_translate("DockWidget", "YZ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Section_tab), _translate("DockWidget", "Section", None))
        self.CutWire_button_apply.setText(_translate("DockWidget", "Apply", None))
        self.CutWire_button_reset.setText(_translate("DockWidget", "Reset", None))
        self.label_2.setText(_translate("DockWidget", "Start", None))
        self.label_3.setText(_translate("DockWidget", "End", None))
        self.CutWire_CheckBox_gap.setText(_translate("DockWidget", "constant gap", None))
        self.groupBox_2.setTitle(_translate("DockWidget", "Object", None))
        self.CutWire_button_select_object.setText(_translate("DockWidget", "Select Object", None))
        self.CutWire_comboBox.setItemText(0, _translate("DockWidget", "Left", None))
        self.CutWire_comboBox.setItemText(1, _translate("DockWidget", "Right", None))
        self.CutWire_comboBox.setItemText(2, _translate("DockWidget", "Both", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CutWire_tab), _translate("DockWidget", "Cut wire", None))
        self.groupBox_3.setTitle(_translate("DockWidget", "Object", None))
        self.LeadingEdge_button_select_object.setText(_translate("DockWidget", "Select Object", None))
        self.LeadingEdge_comboBox.setItemText(0, _translate("DockWidget", "Left", None))
        self.LeadingEdge_comboBox.setItemText(1, _translate("DockWidget", "Right", None))
        self.LeadingEdge_comboBox.setItemText(2, _translate("DockWidget", "Both", None))
        self.label_5.setText(_translate("DockWidget", "<html><head/><body><p>Root</p><p>Start</p></body></html>", None))
        self.label_6.setText(_translate("DockWidget", "<html><head/><body><p>Root</p><p>End</p></body></html>", None))
        self.LeadingEdge_CheckBox_gap.setText(_translate("DockWidget", "constant gap", None))
        self.LeadingEdge_button_apply.setText(_translate("DockWidget", "Apply", None))
        self.LeadingEdge_button_reset.setText(_translate("DockWidget", "Reset", None))
        self.label_4.setText(_translate("DockWidget", "<html><head/><body><p>Tip</p><p>Start</p></body></html>", None))
        self.LeadingEdge_CheckBox_EqualRoot.setText(_translate("DockWidget", "equal to root", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LeadingEdge_tab), _translate("DockWidget", "Leading edge", None))
        self.Close_button.setText(_translate("DockWidget", "Close", None))

