# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WingDial.ui'
#
# Created: Sat Apr 28 22:10:23 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(365, 603)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:Aile-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DockWidget.setWindowIcon(icon)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.Section_tab = QtGui.QWidget()
        self.Section_tab.setObjectName("Section_tab")
        self.gridLayout_4 = QtGui.QGridLayout(self.Section_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Section_horizontalSlider = QtGui.QSlider(self.Section_tab)
        self.Section_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Section_horizontalSlider.setObjectName("Section_horizontalSlider")
        self.gridLayout_4.addWidget(self.Section_horizontalSlider, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Section_button_apply = QtGui.QPushButton(self.Section_tab)
        self.Section_button_apply.setAutoDefault(False)
        self.Section_button_apply.setFlat(False)
        self.Section_button_apply.setObjectName("Section_button_apply")
        self.horizontalLayout.addWidget(self.Section_button_apply)
        self.Section_button_reset = QtGui.QPushButton(self.Section_tab)
        self.Section_button_reset.setAutoDefault(False)
        self.Section_button_reset.setObjectName("Section_button_reset")
        self.horizontalLayout.addWidget(self.Section_button_reset)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_4.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.Section_dial = QtGui.QDial(self.Section_tab)
        self.Section_dial.setObjectName("Section_dial")
        self.gridLayout_4.addWidget(self.Section_dial, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.Section_tab)
        self.groupBox.setMaximumSize(QtCore.QSize(281, 16777215))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Section_button_select_object = QtGui.QPushButton(self.groupBox)
        self.Section_button_select_object.setMinimumSize(QtCore.QSize(130, 31))
        self.Section_button_select_object.setMaximumSize(QtCore.QSize(250, 40))
        self.Section_button_select_object.setObjectName("Section_button_select_object")
        self.gridLayout_2.addWidget(self.Section_button_select_object, 1, 0, 1, 1)
        self.Section_info_selected_object = QtGui.QLineEdit(self.groupBox)
        self.Section_info_selected_object.setEnabled(False)
        self.Section_info_selected_object.setMinimumSize(QtCore.QSize(0, 0))
        self.Section_info_selected_object.setMaximumSize(QtCore.QSize(250, 16777215))
        self.Section_info_selected_object.setObjectName("Section_info_selected_object")
        self.gridLayout_2.addWidget(self.Section_info_selected_object, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.Section_doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.Section_doubleSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Section_doubleSpinBox.setObjectName("Section_doubleSpinBox")
        self.gridLayout_3.addWidget(self.Section_doubleSpinBox, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 5, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons:Section.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Section_tab, icon1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.Close_button = QtGui.QPushButton(self.dockWidgetContents)
        self.Close_button.setObjectName("Close_button")
        self.horizontalLayout_2.addWidget(self.Close_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(QtGui.QApplication.translate("DockWidget", "Wing toolkit", None, QtGui.QApplication.UnicodeUTF8))
        self.Section_button_apply.setText(QtGui.QApplication.translate("DockWidget", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.Section_button_reset.setText(QtGui.QApplication.translate("DockWidget", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DockWidget", "Object", None, QtGui.QApplication.UnicodeUTF8))
        self.Section_button_select_object.setText(QtGui.QApplication.translate("DockWidget", "Select Object", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DockWidget", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Section_tab), QtGui.QApplication.translate("DockWidget", "Section", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("DockWidget", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.Close_button.setText(QtGui.QApplication.translate("DockWidget", "Close", None, QtGui.QApplication.UnicodeUTF8))

